// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vyeqzbbnvmtgvhmbgduc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZXF6YmJudm10Z3ZobWJnZHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5ODUyMTYsImV4cCI6MjA4MTU2MTIxNn0.zzrWkeRMdEFj79OshV4gCXPE14czoEi-Y4qiyeHOn3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
